#!/bin/bash

# bash environment setup, aliases and functions
# Avi Silver 2018

alias ebash='vim ~/.bash_setup'
alias rebash='. ~/.bashrc'

export PYTHONSTARTUP=~/bin/util_scripts/pythonstartup.py
alias wenv='env | sort | grep -i'
